name=['cat','dog','elephant','tiger','donkey']
print(name)
print(name[0])
print(name[2:4])
print(name[1:4][1])
name1=("Flowers","cats","Dogs")
print(name1)
print(name1[0]) 
dict={"name":"elephant","city":"mumbai"}
print(dict["name"])
print(dict)
print(dict["name"][0])